// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/repo/contracts.go
//
// Generated by this command:
//
//	mockgen -source ./internal/repo/contracts.go -destination ./internal/usecase/mocks_repo_test.go -package usecase_test
//

// Package usecase_test is a generated GoMock package.
package usecase_test

import (
	context "context"
	reflect "reflect"
	time "time"

	entity "github.com/andreyxaxa/calendar/internal/entity"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockEventsRepo is a mock of EventsRepo interface.
type MockEventsRepo struct {
	ctrl     *gomock.Controller
	recorder *MockEventsRepoMockRecorder
	isgomock struct{}
}

// MockEventsRepoMockRecorder is the mock recorder for MockEventsRepo.
type MockEventsRepoMockRecorder struct {
	mock *MockEventsRepo
}

// NewMockEventsRepo creates a new mock instance.
func NewMockEventsRepo(ctrl *gomock.Controller) *MockEventsRepo {
	mock := &MockEventsRepo{ctrl: ctrl}
	mock.recorder = &MockEventsRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventsRepo) EXPECT() *MockEventsRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockEventsRepo) Create(arg0 context.Context, arg1 int, arg2 uuid.UUID, arg3 entity.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockEventsRepoMockRecorder) Create(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockEventsRepo)(nil).Create), arg0, arg1, arg2, arg3)
}

// Delete mocks base method.
func (m *MockEventsRepo) Delete(arg0 context.Context, arg1 int, arg2 uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockEventsRepoMockRecorder) Delete(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockEventsRepo)(nil).Delete), arg0, arg1, arg2)
}

// GetEventsForDay mocks base method.
func (m *MockEventsRepo) GetEventsForDay(arg0 context.Context, arg1 int, arg2 time.Time) (map[uuid.UUID]entity.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEventsForDay", arg0, arg1, arg2)
	ret0, _ := ret[0].(map[uuid.UUID]entity.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEventsForDay indicates an expected call of GetEventsForDay.
func (mr *MockEventsRepoMockRecorder) GetEventsForDay(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEventsForDay", reflect.TypeOf((*MockEventsRepo)(nil).GetEventsForDay), arg0, arg1, arg2)
}

// GetEventsForMonth mocks base method.
func (m *MockEventsRepo) GetEventsForMonth(arg0 context.Context, arg1 int, arg2 time.Time) (map[uuid.UUID]entity.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEventsForMonth", arg0, arg1, arg2)
	ret0, _ := ret[0].(map[uuid.UUID]entity.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEventsForMonth indicates an expected call of GetEventsForMonth.
func (mr *MockEventsRepoMockRecorder) GetEventsForMonth(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEventsForMonth", reflect.TypeOf((*MockEventsRepo)(nil).GetEventsForMonth), arg0, arg1, arg2)
}

// GetEventsForWeek mocks base method.
func (m *MockEventsRepo) GetEventsForWeek(arg0 context.Context, arg1 int, arg2 time.Time) (map[uuid.UUID]entity.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEventsForWeek", arg0, arg1, arg2)
	ret0, _ := ret[0].(map[uuid.UUID]entity.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEventsForWeek indicates an expected call of GetEventsForWeek.
func (mr *MockEventsRepoMockRecorder) GetEventsForWeek(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEventsForWeek", reflect.TypeOf((*MockEventsRepo)(nil).GetEventsForWeek), arg0, arg1, arg2)
}

// Update mocks base method.
func (m *MockEventsRepo) Update(arg0 context.Context, arg1 int, arg2 uuid.UUID, arg3 string, arg4 time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockEventsRepoMockRecorder) Update(arg0, arg1, arg2, arg3, arg4 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockEventsRepo)(nil).Update), arg0, arg1, arg2, arg3, arg4)
}
